return {
    schema = 1,
    generated = "2026-07-24T11:14:07+00:00",
    packages = {
        {
            folder = "borne",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/borne/common/network",
                "files/borne/common/protocol",
                "files/borne/gui",
                "files/borne/logger",
                "files/borne/scheduler",
                "files/borne/terminal",
                "files/borne/workers",
                "files/startup",
                "package.lua",
            },
        },
        {
            folder = "chef",
            version = "7.2.2",
            files = {
                "changelog.lua",
                "files/craftbot/ae",
                "files/craftbot/chef",
                "files/craftbot/common/network",
                "files/craftbot/common/protocol",
                "files/craftbot/crafter",
                "files/craftbot/inventory",
                "files/craftbot/items",
                "files/craftbot/logger",
                "files/craftbot/networkManager",
                "files/craftbot/recipeManager",
                "files/craftbot/recipes/bacon",
                "files/craftbot/recipes/baconcheeseburger",
                "files/craftbot/recipes/beurre",
                "files/craftbot/recipes/burger",
                "files/craftbot/recipes/burgervegan",
                "files/craftbot/recipes/cacao",
                "files/craftbot/recipes/caramel",
                "files/craftbot/recipes/cheeseburger",
                "files/craftbot/recipes/coca",
                "files/craftbot/recipes/deluxeburger",
                "files/craftbot/recipes/donutcaramel",
                "files/craftbot/recipes/donutcarotte",
                "files/craftbot/recipes/donutchoco",
                "files/craftbot/recipes/donutcitrouille",
                "files/craftbot/recipes/donutglace",
                "files/craftbot/recipes/donutmiel",
                "files/craftbot/recipes/donutpomme",
                "files/craftbot/recipes/donutsprinkles",
                "files/craftbot/recipes/donutsucre",
                "files/craftbot/recipes/farine",
                "files/craftbot/recipes/firmtofu",
                "files/craftbot/recipes/frite",
                "files/craftbot/recipes/groundbeef",
                "files/craftbot/recipes/huile",
                "files/craftbot/recipes/mcpam",
                "files/craftbot/recipes/menucomplet",
                "files/craftbot/recipes/pain",
                "files/craftbot/recipes/pate",
                "files/craftbot/recipes/poivre",
                "files/craftbot/recipes/relish",
                "files/craftbot/recipes/saucesoja",
                "files/craftbot/recipes/sel",
                "files/craftbot/recipes/silkentofu",
                "files/craftbot/recipes/sucre",
                "files/craftbot/recipes/tofeak",
                "files/craftbot/test",
                "files/startup",
                "package.lua",
            },
        },
        {
            folder = "moniteur",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/moniteur/common/network",
                "files/moniteur/common/protocol",
                "files/moniteur/monitor",
                "files/startup",
                "package.lua",
            },
        },
        {
            folder = "server",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/craftbot/common/network",
                "files/craftbot/common/protocol",
                "files/craftbot/reservationManager",
                "files/craftbot/server",
                "files/startup",
                "package.lua",
            },
        },
    },
}
