return {
    schema = 1,
    managerVersion = "1.5.3",
    managerFiles = {
        "config/repository.lua",
        "config/settings.lua",
        "core/backup.lua",
        "core/checksum.lua",
        "core/filesystem.lua",
        "core/installed.lua",
        "core/installer.lua",
        "core/logger.lua",
        "core/packages.lua",
        "core/remote.lua",
        "core/repair.lua",
        "core/uninstaller.lua",
        "core/updater.lua",
        "core/verifier.lua",
        "core/version.lua",
        "ui/menu.lua",
        "ui/progress.lua",
        "ui/theme.lua",
        "manager.lua",
        "update-manager.lua",
        "startup",
    },
    packages = {
        {
            folder = "borne",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/borne/common/network",
                "files/borne/common/protocol",
                "files/borne/gui",
                "files/borne/logger",
                "files/borne/scheduler",
                "files/borne/terminal",
                "files/borne/workers",
                "files/startup",
                "package.lua",
            }
        },
        {
            folder = "chef",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/craftbot/ae",
                "files/craftbot/chef",
                "files/craftbot/common/network",
                "files/craftbot/common/protocol",
                "files/craftbot/crafter",
                "files/craftbot/inventory",
                "files/craftbot/items",
                "files/craftbot/logger",
                "files/craftbot/networkManager",
                "files/craftbot/recipeManager",
                "files/craftbot/recipes/bacon",
                "files/craftbot/recipes/baconcheeseburger",
                "files/craftbot/recipes/burger",
                "files/craftbot/recipes/burgervegan",
                "files/craftbot/recipes/cacao",
                "files/craftbot/recipes/cheeseburger",
                "files/craftbot/recipes/coca",
                "files/craftbot/recipes/deluxeburger",
                "files/craftbot/recipes/donutchoco",
                "files/craftbot/recipes/farine",
                "files/craftbot/recipes/firmtofu",
                "files/craftbot/recipes/frite",
                "files/craftbot/recipes/groundbeef",
                "files/craftbot/recipes/huile",
                "files/craftbot/recipes/mcpam",
                "files/craftbot/recipes/menucomplet",
                "files/craftbot/recipes/pain",
                "files/craftbot/recipes/pate",
                "files/craftbot/recipes/poivre",
                "files/craftbot/recipes/relish",
                "files/craftbot/recipes/saucesoja",
                "files/craftbot/recipes/sel",
                "files/craftbot/recipes/silkentofu",
                "files/craftbot/recipes/sucre",
                "files/craftbot/recipes/tofeak",
                "files/craftbot/test",
                "files/startup",
                "package.lua",
            }
        },
        {
            folder = "moniteur",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/moniteur/common/network",
                "files/moniteur/common/protocol",
                "files/moniteur/monitor",
                "files/startup",
                "package.lua",
            }
        },
        {
            folder = "server",
            version = "7.1.1",
            files = {
                "changelog.lua",
                "files/craftbot/common/network",
                "files/craftbot/common/protocol",
                "files/craftbot/reservationManager",
                "files/craftbot/server",
                "files/startup",
                "package.lua",
            }
        },
    }
}
